### PR TITLE
Add TSLint checks action

### PR DESCRIPTION
**Pull request by mooyoul**
This is first Github action that supports TSLint 🎉

### CODE REVIEW

**Comment by mooyoul** [comment]
@gep13  Oh sorry, I missed that point. BTW Do you have any ideas about grouping?

**Comment by gep13** [comment]
>@mooyoul said...
Do you have any ideas about grouping?

To be honest, no.  I haven't looked at the potential for sub-groups yet.  I just know that there have been a few pull requests recently that have started placing links beside other, similar, actions and this is a good indication that additional groups are required.

If you wanted to take a stab at doing that, after this PR is merged, I would welcome the help.

**Comment by mooyoul** [comment]
Okay, just pushed a new commit :)

**Comment by gep13** [comment]
@mooyoul thank you for updating your PR.

Your changes have been merged, thanks for your contribution 👍

**Pull request merged**
