### PR TITLE
Add entry to publish Google analytics using Github Pages

### PR DESCRIPTION
**Pull request by cristianpb**
I wrote an article about how to publish google analytics stats to github pages https://cristianpb.github.io/blog/analytics-google

### CODE REVIEW

**Comment by peaceiris** [comment]
Screen Shot 2019-11-17 at 13 07 46

`GITHUB_TOKEN` works only on a **private** repository. I recommend you to use `ACTIONS_DEPLOY_KEY` or `PERSONAL_TOKEN`

cf. the latest readme [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages)

**Comment by cristianpb** [comment]
Thanks for your comment @peaceiris 
I have modified that in my github action code but not in the blog post.
Now it should be OK.

**Comment by peaceiris** [comment]
It might be helpful for your readers that your article has the link to [the readme](https://github.com/peaceiris/actions-gh-pages).

**Comment by cristianpb** [comment]
@peaceiris  I did that here https://github.com/cristianpb/cristianpb.github.io/commit/9732e31d1480c581a412b0c1825205b7b6311b2a

**Comment by peaceiris** [comment]
LGTM and thank you for sharing it!

**Comment by gep13** [comment]
@cristianpb your changes have been merged, thanks for your contribution 👍

**Pull request merged**
