### PR TITLE
Typo: commited -> committed

### PR DESCRIPTION
**Pull request by spekulatius**
Just a typo @sdras...

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@spekulatius the linting error isn't related to this change, so happy to merge this.

**Comment by gep13** [comment]
@spekulatius your changes have been merged, thanks for your contribution 👍

**Comment by spekulatius** [comment]
Awesome, thank you for checking it @gep13!

**Pull request merged**
