### PR TITLE
Add Action to Check Project Dependencies

### PR DESCRIPTION
**Pull request by lauragift21**
[https://github.com/iheanyi/licensed-action](https://github.com/iheanyi/licensed-action)

### CODE REVIEW

**Comment by sdras** [comment]
This is a great addition, @lauragift21! The only thing missing though is the repo doesn't have a README about the project. @iheanyi are you ok with adding a README to your project?

**Comment by iheanyi** [comment]
@sdras Yeah, I definitely am okay with adding a README to it. It's not 100% ready just yet (hack week project at work, still working on it. Will have one added within a week or so. :D

**Comment by lauragift21** [comment]
Right! I saw it and didn't want to miss the chance to add it the list. @iheanyi great work maybe when you have the README ready @sdras can merge it.

**Comment by iheanyi** [comment]
@lauragift21 Most definitely, I'll keep you all in the loop!

**Comment by sdras** [comment]
Awesome! Thanks everyone!

**Comment by iheanyi** [comment]
@sdras Added a README to my project finally. :)

**Comment by lauragift21** [comment]
Yay! Thanks @iheanyi I'll go ahead and fix the merge conflicts.

**Comment by gep13** [comment]
@lauragift21 thank you for updating the PR, and thanks to @iheanyi for creating this action.

**Pull request merged**
