### PR TITLE
Add GitHub Action for Firebase

### PR DESCRIPTION
**Pull request by w9jds**

### CODE REVIEW

**Comment by boyney123** [comment]
Hey @w9jds    

Just to let you know I have added you're action to a website I created to list actions: 

https://github-actions.netlify.com/

**Comment by gep13** [comment]
@sdras this seems to provide similar functionality to what is provided in this PR: https://github.com/sdras/awesome-actions/pull/48

Perhaps once everything is merged in, and re-structured, we might want to think about putting similar actions together?

**Comment by w9jds** [comment]
Yes, I noticed that. Mine is already on the github actions marketplace and I created it in the end of November and forgot to add a pull request here. If you want to use the other one that is completely fine.

**Comment by gep13** [comment]
@w9jds having multiple actions that do the same, or similar, things is fine.  Just thinking about the best way to group these in the readme so that people can find them.

**Comment by sdras** [comment]
I agree that we should add this one in and then restructure redundant ones 👍

**Pull request merged**
