### PR TITLE
Add GitHub Actions for Golang

### PR DESCRIPTION
**Pull request by cedrickring**
This action sets up your workspace to run `go` (or other) commands in it.

### CODE REVIEW

**Comment by cedrickring** [comment]
Sure :)

**Comment by boyney123** [comment]
Hey @cedrickring ,

I have added you're action to https://github-actions.netlify.com

You're action is here: https://github-actions.netlify.com/golang

👍

**Comment by sdras** [comment]
Looks great thanks!

**Comment by cedrickring** [comment]
@boyney123 oh cool, thanks 👍

**Pull request merged**
