### PR TITLE
chore(docs): update README with lighthouse-check-action.

### PR DESCRIPTION
**Pull request by adamhenson**
# Changes
- Adds `lighthouse-check-action`.

### CODE REVIEW

**Comment by peaceiris** [comment]
It is good to add a new link at end of the section.

**Comment by adamhenson** [comment]
Well it was a nice try on my part 😆- updated in fddefda5 (@peaceiris).

**Comment by peaceiris** [comment]
LGTM. Thank you for sharing it.

**Comment by gep13** [comment]
@adamhenson thank you!

**Comment by adamhenson** [comment]
Thanks @gep13!

**Pull request merged**
