### PR TITLE
adding organization and containertree github pages generator action

### PR DESCRIPTION
**Pull request by vsoch**
Hey @sdras ! Per your note in my first pull request, I've given a first shot at an organization for the actions below, note that my previously submit action (for the funny Confucius messages) is now under notifications and messages. The other categories are still fairly general, and I created based on what I saw in the list. This PR will also add the [containertree example](https://github.com/vsoch/containertree) that I put together yesterday, allowing a user to deploy an interactive tree diagram for their Dockerfile to Github pages.

I hope these are awesome enough!

### CODE REVIEW

**Comment by gep13** [comment]
@sdras given the amount of open PR's, perhaps it would be best to leave this re-structuring until all the current PR's are merged, at which point, there should be less re-work for those PR's.  i.e. only one PR to update, rather than update the other 30.  What do you think?

**Comment by vsoch** [comment]
I think she is probably too busy to respond to any of them :/ But definitely that is a good idea!

**Comment by gep13** [comment]
@vsoch my understanding is that @sdras is going to attempt to go these PR's this weekend.  I am just trying to help by doing an initial triage of the open PR's.

**Comment by vsoch** [comment]
Woohoo great news! After all the PRs Is be happy to do this one over with a proposed organization. Thanks for the update @gep13 I’m so glad this is underway!

**Comment by gep13** [comment]
>@vsoch said...
After all the PRs Is be happy to do this one over with a proposed organization.

That is great news, thank you very much!

**Comment by sdras** [comment]
Yesss this is awesome. I've gone through a lot of them, but still have some more that I'll finish up tomorrow. If you'd be willing to fix up the PR then, I would be grateful. Thanks!

**Comment by vsoch** [comment]
Definitely.

**Comment by gep13** [comment]
@vsoch I have just merged some of the PR's that were outstanding on this repository.  Would it be possible for you to update your PR one more time, and then we can look to getting your PR merged?

Thanks!

**Comment by vsoch** [comment]
Yeah! Taking a look now.

**Comment by vsoch** [comment]
okay done! I carefully went through the merges from the last four days and made sure to get every addition. Note that one of the addition of one had a broken link, so I updated the link to the (renamed) folder -> https://github.com/repetitive/actions/tree/master/auto-pull-request

**Comment by sdras** [comment]
I love this! This is the best, I so appreciate your effort here. Thank you!

**Pull request merged**
