### PR TITLE
Bump version of max/awesome-lint

### PR DESCRIPTION
**Pull request by max**
I just cut a new version of max/awesome-lint that makes use of the new GitHub Actions format. This updates the lint workflow to make use of it.

### CODE REVIEW

**Comment by xt0rted** [comment]
Dependabot has basic support for bumping actions now to make this easier going forward.

https://github.com/dependabot/dependabot-core/pull/1313

**Comment by gep13** [comment]
>@xt0rted said...
Dependabot has basic support for bumping actions now to make this easier going forward.

Ooo, I hadn't heard about this feature of Dependabot, that is good to know, thanks!  I do not believe that I would have permissions to add dependabot onto this repository.  We would need @sdras to help with that.

**Comment by gep13** [comment]
@max thanks for adding this!

**Comment by gep13** [comment]
@max your changes have been merged, thanks for your contribution 👍

**Pull request merged**
