### PR TITLE
Added `gha` script link.

### PR DESCRIPTION
**Pull request by tschoffelen**
This adds a link to the `gha` utility that I've built, which allows you to test your workflows locally using Docker.

### CODE REVIEW

**Comment by gep13** [comment]
@tschoffelen this is very cool!  Great work! 😄

**Comment by tschoffelen** [comment]
Thanks @gep13!

**Comment by sdras** [comment]
Hey, please don't put yours at the top, you can see in the contributing guide that you're supposed to put yours at the bottom. It's been a little bit, so you can put it somewhere near the middle, but not at the top.

**Comment by tschoffelen** [comment]
@sdras Apologies, added it to the bottom now!

**Comment by sdras** [comment]
Excellent, thank you!

**Pull request merged**
