### PR TITLE
Add github-slug-action to Utility section

### PR DESCRIPTION
**Pull request by rlespinasse**

### CODE REVIEW

**Comment by gep13** [comment]
@rlespinasse is there a reason that you have also change the table of contents on this page?

**Comment by rlespinasse** [comment]
@gep13 I don't change it, I will revert this change in my PR.

**Comment by rlespinasse** [comment]
@gep13 it's fix

**Comment by gep13** [comment]
@rlespinasse your changes have been merged, thanks for your contribution 👍  Thank you for taking the time to fix that up!

**Pull request merged**
