### PR TITLE
Add tutorial link for integrating Github actions with Rails

### PR DESCRIPTION
**Pull request by the-spectator**
+ Mention GoRails tutorial for setting Github actions CI for rails

### CODE REVIEW

**Comment by sdras** [comment]
Can you please add it to the end of the list? Thanks!

**Comment by the-spectator** [comment]
@sdras Appended the tutorial link at the end of the list. Thanks for the review.

**Comment by gep13** [comment]
@the-spectator your changes have been merged, thanks for your contribution 👍

**Comment by the-spectator** [comment]
@sdras @gep13 Thank you for the merge!!

**Pull request merged**
