### PR TITLE
Add Docker's Build and push Docker images action.

### PR DESCRIPTION
**Pull request by tao12345666333**
ref: https://github.com/marketplace/actions/build-and-push-docker-images

### CODE REVIEW

**Comment by jessicalostinspace** [comment]
I feel this may better be under collections of Actions for Docker - quite possibly under this link which links to the build and push action: https://github.com/docker/github-actions

**Comment by tao12345666333** [comment]
@jessicalostinspace  Thanks for your advice. Updated.

**Comment by jessicalostinspace** [comment]
Looks good to me. You may have to pull master and push up again since there is a temporary disable on linter check.

**Comment by tao12345666333** [comment]
👌

**Comment by tao12345666333** [comment]
Done.

**Pull request merged**
