### PR TITLE
Remove stale / deprecated / HCL-only resources

### PR DESCRIPTION
**Pull request by DannyBen**
This draft PR marks stale, outdated and deprecated resources, hoping to get a second opinion before removing important resources.

Resources marked with ❌ should probably be removed.
Resources marked with ❓ should be considered for removal.

I would love to get some input from one of the main collaborators, before moving on to deletion.

At first I considered whether they should be removed, or moved to a different location (or remain permanently marked as "v1"), but the big majority of the marked elements seem completely abandoned, or at least, without any attention from their authors. Since this is the "Awesome GitHub Actions" list and not the "All GitHub Actions" list - I considered abandoned/unmaintained repos "not awesome".

[See the marked README](https://github.com/DannyBen/awesome-actions/blob/hcl-cleanup/README.md).

cc: #158 

---

### Changes

- Removed all HCL-only resources
- Removed Internet of Things category, since it only had one deprecated resource
- Removed mentions such as "supports the new YAML syntax"
- Placed the two "GitHub Actions for Yarn" next to each other
- Changed link to "Snyk Test Action" to the official one (https://github.com/clarkio/snyk-cli-action/issues/3#issuecomment-582050799)
- Changed link for "Automatically add reviewers to pull request based on the configuration file" to go directly to its action repository

### CODE REVIEW

**Comment by gep13** [comment]
@peaceiris can I get your thoughts on this one? Thanks

**Comment by peaceiris** [comment]
I have checked all the changes of this Pull Request.

Yes! All marked link is for the GitHub Actions beta v1 (HCL syntax) not the v2 YAML.

I agree with this suggestion.

@DannyBen Great work!

**Comment by DannyBen** [comment]
> I agree with this suggestion.

Great. So I will submit an updated file with all the marked items removed.

**Comment by peaceiris** [comment]
LGTM!

**Comment by DannyBen** [comment]
Ok - I undrafted it, it is ready for you now.

I added details in the description - all these were already done in the first commit, I just thought I should state them clearly for posterity.

**Comment by gep13** [comment]
@peaceiris thanks for taking a look at this.  I am more than happy to merge this based on your and @DannyBen feedback here.

Going forward, when looking at new additions to this list, what exactly should I, or others, be looking for, specifically?

**Comment by gep13** [comment]
@DannyBen huge thank you for taking this on, and getting it all updated!  Really appreciate it!

**Comment by DannyBen** [comment]
My pleasure.

> Going forward, when looking at new additions to this list, what exactly should I, or others, be looking for, specifically?

Although I am not sure this question was directed at me - as it is more of a policy question - I would like to provide my thoughts here, since as a GitHub Actions user, I found quite a few questionable resources in this awesome list.

- Resources that show the HCL syntax or show the old visual workflow editor should not be accepted.
   - The exception to this is established actions with a lot of stars (>50) that also mention the YAML syntax (and only have the HCL for backwards compatibility).
- Actions that are developed by users (as opposed to official actions), should be more carefully examined.
   - If they have less than 10 stars, I would search to see if there is a better or official similar action.

In addition, I would consider:

- Updating the collection to have a clear distinction between what is an action, and what is not.
- Adding an "Official Vendor Actions" section - which will hold actions from companies that provide actions to their own products (snyk, aws for example).

**Pull request merged**
