### PR TITLE
Add setup-php action

### PR DESCRIPTION
**Pull request by Luc45**
This PR adds an action to setup PHP.

### CODE REVIEW

**Comment by rivasiris** [comment]
Add setup-php action

**Comment by rivasiris** [comment]
Add setup-php action

**Comment by peaceiris** [comment]
The section is for the official resources. Did the setup action become official?

**Comment by peaceiris** [comment]
This pr seems to be a duplicate of https://github.com/sdras/awesome-actions/pull/168, maybe we can close this.

**Comment by Luc45** [comment]
PHP is not a tool, it's a language. Should be in the same section of Java, not Composer.

Perhaps we could just move the link from that PR to the appropriate section? I can do that in this PR if you'd like.

**Comment by jessicalostinspace** [comment]
I meant to close this as mentioned above, it's a duplicate of #168 .

**Pull request merged**
